name: Coriolis Unit Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r test-requirements.txt
    - name: Run unit tests
      run: |
        python -m nose -v --nocapture --logging-level=ERROR coriolis/tests
